#!/usr/bin/env ruby
require_relative 'app'

class Main
  def initialize
    @app = App.new
    puts "Welcome to School Library App!\n"
  end

  def interface
    puts "\nPlease choose an option by entering a number:"
    puts '1 - List all books'
    puts '2 - List all people'
    puts '3 - Create a person'
    puts '4 - Create a book'
    puts '5 - Create a rental'
    puts '6 - List all rentals for a given person id'
    puts '7 - Exit'
  end

  def menu
    loop do
      interface
      selection = gets.chomp.to_i
      case selection
      when 1 then @app.list_books
      when 2 then @app.list_people
      when 3 then @app.create_person
      when 4 then @app.create_book
      when 5 then @app.create_rental
      when 6 then @app.list_rental
      else
        puts "Don't say goodbye, bye, bye..."
        exit
      end
    end
  end
end

Main.new.menu
